name: wordsapp
description: "An app to store your new words."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^13.0.0
  http: ^1.2.2
  flutter_slidable: ^3.1.2
  dropdown_button2: ^2.3.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/folders/folder_pink.png
    - Assets/secondcolor/search.png
    - Assets/secondcolor/book-bookmark.png
    - Assets/secondcolor/menu-burger.png
    - Assets/firstcolor/book-bookmark-2.png
    - Assets/firstcolor/menu-burger-2.png
    - Assets/firstcolor/plus.png
    - Assets/firstcolor/search-2.png
    - Assets/firstcolor/game-rules-2.png
    - Assets/secondcolor/game-rules.png
    - Assets/firstcolor/book.png
    - Assets/firstcolor/badge.png
    - Assets/firstcolor/clock-three.png
    - Assets/folders/folder_blue.png
    - Assets/folders/folder_brown.png
    - Assets/folders/folder_orange.png
    - Assets/folders/folder_green.png
    - Assets/folders/folder_gold.png
    - Assets/firstcolor/plus-2.png
    - Assets/firstcolor/pencil.png
    - Assets/firstcolor/pin.png
    - Assets/secondcolor/pin2.png
    - Assets/firstcolor/search-3.png
    - Assets/secondcolor/speaker.png
    - Assets/firstcolor/linking.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: cool
        fonts:
          - asset: fonts/PlaywriteCU-VariableFont_wght.ttf
      - family: roboto
        fonts:
          - asset: fonts/static/Raleway-Medium.ttf
      
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages